alias: "Enhanced Entrance Motion Lighting"
description: "Motion-activated lighting with adaptive brightness and improved timing"
triggers:
  - type: motion
    device_id: b1b329d4ce5d2ab76da71acd1fc3c4a2
    entity_id: edba6ca93c009b956f6a4c0576bb40cf
    domain: binary_sensor
    enabled: true
    trigger: device
conditions:
  - condition: device
    type: is_illuminance
    device_id: b1b329d4ce5d2ab76da71acd1fc3c4a2
    entity_id: 47aa27734897d9ee4a999b25f9947a89
    domain: sensor
    below: 28
actions:
  - choose:
      - conditions:
          - condition: time
            after: "02:00:00"
            before: "06:00:00"
        sequence:
          - target:
              area_id: entrance
            data:
              transition: 60
              brightness_pct: 5
              kelvin: 2000
            action: light.turn_on
          - wait_for_trigger:
              - entity_id:
                  - binary_sensor.bewegungssensor1_occupancy
                from: "on"
                to: "off"
                for:
                  hours: 0
                  minutes: 0
                  seconds: 0
                trigger: state
          - target:
              device_id: 7b0d4d742e2cb0a88174bc5e0eda52eb
            data:
              transition: 20
            action: light.turn_off
      - conditions:
          - condition: time
            after: "21:00:00"
            before: "02:00:00"
        sequence:
          - target:
              area_id: entrance
            data:
              transition: 60
              brightness_pct: 70
              kelvin: 2837
            action: light.turn_on
          - wait_for_trigger:
              - entity_id:
                  - binary_sensor.bewegungssensor1_occupancy
                to: "off"
                for:
                  hours: 0
                  minutes: 1
                  seconds: 0
                trigger: state
          - target:
              device_id: 7b0d4d742e2cb0a88174bc5e0eda52eb
            data:
              transition: 20
            action: light.turn_off
    default:
      - target:
          area_id: entrance
        data:
          brightness_pct: 100
          transition: 80
        action: light.turn_on
      - wait_for_trigger:
          - entity_id:
              - binary_sensor.bewegungssensor1_occupancy
            to: "off"
            for:
              hours: 0
              minutes: 3
              seconds: 0
            trigger: state
      - target:
          device_id: 7b0d4d742e2cb0a88174bc5e0eda52eb
        data:
          transition: 10
        action: light.turn_off
mode: restart
