alias: Turn OFF everything when 4h no motion
description: ""
triggers:
  - type: no_motion
    device_id: b1b329d4ce5d2ab76da71acd1fc3c4a2
    entity_id: edba6ca93c009b956f6a4c0576bb40cf
    domain: binary_sensor
    for:
      hours: 4
      minutes: 0
      seconds: 0
    trigger: device
conditions: []
actions:
  - metadata: {}
    data: {}
    target:
      area_id:
        - schlafzimmer
        - entrance
        - wohnzimmer
        - kuche
        - durchgangszimmer
    action: light.turn_off
  - metadata: {}
    data: {}
    target:
      area_id:
        - wohnzimmer
        - schlafzimmer
    action: switch.turn_off
mode: single
