alias: livingroom_on_motion
description: Motion-activated lighting
triggers:
  - trigger: state
    entity_id: binary_sensor.bewegungssensor1_occupancy
    to: "on"
conditions:
  - condition: state
    entity_id: switch.smart_desk_lamp
    state: "off"
  - condition: numeric_state
    entity_id: sensor.bewegungssensor2_licht_illuminance
    below: 20
  - condition: time
    after: "14:00:00"
    before: "22:00:00"
actions:
  - action: switch.turn_on
    target:
      entity_id: switch.smart_desk_lamp
  - action: light.turn_on
    data:
      transition: 2
    target:
      area_id: wohnzimmer
mode: restart
