id: low_temperature_alert
alias: Low Temperature Alert
description: Notify when room temperature drops below 15°C
triggers:
  - entity_id: sensor.wohnzimmersensor_temperature
    below: 15
    trigger: numeric_state
    id: Wohnzimmer
    for:
      minutes: 5
  - entity_id: sensor.badsensor_temperature
    below: 15
    trigger: numeric_state
    id: Bad
    for:
      minutes: 5
conditions: []
actions:
  - service: notify.mobile_app_pixel_9_pro
    data:
      title: "Temperatur Warnung"
      message: "{{ trigger.id }} ist bei {{ trigger.to_state.state | round(1) }}°C"
  - service: notify.mobile_app_oppo_sandra
    data:
      title: "Temperatur Warnung"
      message: "{{ trigger.id }} ist bei {{ trigger.to_state.state | round(1) }}°C"
mode: single
