id: turn_off_everything_on_6h_no_motion
alias: Turn OFF everything when 6h no motion
description: ""
triggers:
  - entity_id: binary_sensor.praesenzsensor_presence
    to: "off"
    for:
      hours: 6
      minutes: 0
      seconds: 0
    trigger: state
conditions: []
actions:
  # Turn off all lights in all areas
  - action: light.turn_off
    target:
      area_id:
        - schlafzimmer
        - entrance
        - wohnzimmer
        - kuche
        - durchgangszimmer
  # Turn off all individual lights
  - action: light.turn_off
    target:
      entity_id:
        - light.kuchenlampe
        - light.durchgangszimmer1
        - light.durchgangszimmer2
        - light.wohnzimmerlampe
  # Turn off all switches in all areas
  - action: switch.turn_off
    target:
      area_id:
        - schlafzimmer
        - entrance
        - wohnzimmer
        - kuche
        - durchgangszimmer
  # Turn off Yamaha boxes specifically
  - action: switch.turn_off
    target:
      entity_id:
        - switch.box_left
        - switch.box_right
mode: single
