id: turn_off_everything_on_6h_no_motion
alias: Turn OFF everything when 4h no motion
description: ""
triggers:
  - type: no_motion
    device_id: b1b329d4ce5d2ab76da71acd1fc3c4a2
    entity_id: edba6ca93c009b956f6a4c0576bb40cf
    domain: binary_sensor
    for:
      hours: 4
      minutes: 0
      seconds: 0
    trigger: device
conditions: []
actions:
  # Turn off all lights in all areas
  - action: light.turn_off
    target:
      area_id:
        - schlafzimmer
        - entrance
        - wohnzimmer
        - kuche
        - durchgangszimmer
  # Turn off all individual lights
  - action: light.turn_off
    target:
      entity_id:
        - light.kuchenlampe
        - light.durchgangszimmer1
        - light.durchgangszimmer2
        - light.wohnzimmerlampe
  # Turn off all switches in all areas
  - action: switch.turn_off
    target:
      area_id:
        - schlafzimmer
        - entrance
        - wohnzimmer
        - kuche
        - durchgangszimmer
  # Turn off Yamaha boxes specifically
  - action: switch.turn_off
    target:
      entity_id:
        - switch.box_left
        - switch.box_right
mode: single
