alias: livingroom_on_motion
description: Motion-activated lighting
triggers:
  - trigger: state
    entity_id: binary_sensor.bewegungssensor1_occupancy
    to: "on"
conditions:
  - condition: state
    entity_id: switch.desklamp
    state: "off"
  - condition: numeric_state
    entity_id: sensor.bewegungssensor2_licht_illuminance
    below: 20
  - condition: time
    after: "14:00:00"
    before: "22:00:00"
actions:
  - action: switch.turn_on
    target:
      entity_id: switch.desklamp
  - action: light.turn_on
    data:
      transition: 2
    target:
      area_id: wohnzimmer
  - action: light.turn_on
    data:
      transition: 2
      brightness_pct: 100
    target:
      entity_id: light.wohnzimmerlampe
  - action: light.turn_on
    data:
      transition: 2
      brightness_pct: 20
    target:
      entity_id:
        - light.vintage_lampe
        - light.stehlampe
mode: restart
